import type { Metadata } from 'next';
import './globals.css';
import { GlobalBookContextProvider } from '@/context/bookContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalBookContextProvider>{children}</GlobalBookContextProvider>
      </body>
    </html>
  );
}
